name: flow_forge
description: "FlowForge - Smart Chatbot Flow Builder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700

